# -*- coding: utf-8 -*-
"""Editorial templates use internal categories and explicit, atomic saves.

Provider responses are controlled fixtures. No credentials or external requests
are required, and no existing product descriptions are regenerated by this suite.
"""

from types import SimpleNamespace
from unittest.mock import patch

from lxml import html

from odoo.exceptions import AccessError, MissingError, UserError, ValidationError
from odoo.tests.common import TransactionCase, tagged

from ..controllers.main import BaderProductIntelligenceController
from ..models.content_generation import CONTENT_TEMPLATE_UNSET


@tagged("-at_install", "post_install")
class TestBPIContentTemplates(TransactionCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.service = cls.env["bpi.service"]
        cls.templates = cls.env["bpi.content.template"]
        cls.general = cls.env.ref("bader_product_intelligence.content_template_general")
        cls.instrumental = cls.env.ref("bader_product_intelligence.content_template_instrumental")
        # Keep legacy-renderer fixtures deterministic after an operator selects
        # another supported format. TransactionCase rolls this fixture back.
        cls.instrumental.write({"format": "two_sections", "short_min_words": 45,
                                "short_max_words": 70, "long_min_words": 0, "long_max_words": 0})
        cls.root_category = cls.env["product.category"].create({"name": "BPI Template Root"})
        cls.child_category = cls.env["product.category"].create({
            "name": "Instrumental", "parent_id": cls.root_category.id,
        })
        cls.leaf_category = cls.env["product.category"].create({
            "name": "Espátulas de composite", "parent_id": cls.child_category.id,
        })
        cls.public_category = cls.env["product.public.category"].create({
            "name": "Instrumental - categoría de tienda, no regla editorial",
        })
        cls.product = cls.env["product.template"].create({
            "name": "ESPÁTULA PARA COMPOSITE BPI - NOMBRE EXACTO",
            "default_code": "BPI-CONTENT-TEMPLATE-001",
            "categ_id": cls.leaf_category.id,
            "public_categ_ids": [(6, 0, cls.public_category.ids)],
            "description_sale": "Texto comercial guardado para conservar.",
            "bpi_ai_generated_description": "<p>OLD_AI_NOT_TECHNICAL_EVIDENCE</p>",
            "bpi_technical_description": "<p>OLD_TECH_NOT_CONFIRMED_EVIDENCE</p>",
            "website_meta_title": "SEO que no debe cambiar",
            "bpi_geo_title": "GEO que no debe cambiar",
            "bpi_faq_ids": [(0, 0, {"question": "¿Se conserva?", "answer": "Sí."})],
        })
        cls.non_manager = cls.env["res.users"].with_context(no_reset_password=True).create({
            "name": "BPI Content Templates Internal User",
            "login": "bpi_content_templates_internal_user",
            "groups_id": [(6, 0, [cls.env.ref("base.group_user").id])],
        })
        cls.stock_manager = cls.env["res.users"].with_context(no_reset_password=True).create({
            "name": "BPI Content Templates Native Stock Manager",
            "login": "bpi_content_templates_native_stock_manager",
            "groups_id": [(6, 0, [
                cls.env.ref("base.group_user").id,
                cls.env.ref("stock.group_stock_manager").id,
            ])],
        })

    def setUp(self):
        super().setUp()
        transport = patch.object(
            type(self.service), "_openai_request",
            side_effect=AssertionError("Content-template tests must not call an external provider"),
        )
        self.blocked_transport = transport.start()
        self.addCleanup(transport.stop)
        # TransactionCase fixtures are deliberately uncommitted and cannot be
        # read through the production second-cursor visibility check. Preserve
        # the guard itself while resolving fixture metadata in this transaction.
        # Real cross-transaction freshness is certified separately in QAS.
        def fixture_context(service, product_id, template_id=CONTENT_TEMPLATE_UNSET):
            return service.content_template_context(service._meli_product(product_id), template_id=template_id)

        freshness = patch.object(type(self.service), "_content_template_fresh_context", fixture_context)
        freshness.start()
        self.addCleanup(freshness.stop)

    def _new_template(self, **values):
        defaults = {
            "name": "BPI Template Alternative",
            "short_instructions": "Resumen con datos confirmados.",
            "long_instructions": "Ficha técnica sin inventar características.",
            "format": "free",
        }
        defaults.update(values)
        return self.templates.create(defaults)

    def _snapshot(self):
        return self.product.read([
            "name", "categ_id", "public_categ_ids", "bpi_content_template_id",
            "description_sale", "bpi_ai_generated_description", "bpi_technical_description",
            "website_meta_title", "bpi_geo_title", "bpi_faq_ids", "website_published", "write_date",
        ])[0]

    def _structured_response(self, **values):
        response = {
            "description": "Resumen comercial de la espátula para revisión profesional.",
            "generalParagraphs": [
                "La espátula está destinada al trabajo con composite según su identificación guardada.",
                "Los materiales y las condiciones de mantenimiento requieren datos técnicos confirmados.",
            ],
            "specificationIds": [],
        }
        response.update(values)
        return response

    def _generate(self, response, **kwargs):
        with patch.object(type(self.service), "_openai_json", return_value=response) as provider:
            result = self.service.generate_content(self.product, **kwargs)
        provider.assert_called_once()
        return result, provider.call_args.args[0]

    def test_seed_contract_and_noupdate_preserve_operator_edits(self):
        self.assertEqual(self.general.format, "free")
        self.assertEqual((self.general.short_min_words, self.general.short_max_words), (45, 70))
        self.assertEqual((self.general.long_min_words, self.general.long_max_words), (350, 650))
        self.assertEqual(self.instrumental.format, "two_sections")
        self.assertEqual((self.instrumental.short_min_words, self.instrumental.short_max_words), (45, 70))
        self.assertFalse(self.instrumental.long_min_words)
        self.assertFalse(self.instrumental.long_max_words)
        for name in ("content_template_general", "content_template_instrumental"):
            data = self.env["ir.model.data"].search([
                ("module", "=", "bader_product_intelligence"), ("name", "=", name),
            ])
            self.assertEqual(len(data), 1)
            self.assertTrue(data.noupdate)

    def test_general_fallback_ignores_matching_public_category_name(self):
        context = self.service.content_template_context(self.product)
        self.assertEqual(context["effective"]["id"], self.general.id)
        self.assertEqual(context["source"]["kind"], "general")
        self.assertFalse(context["selectionId"])
        self.assertEqual(context["internalCategory"]["id"], self.leaf_category.id)

    def test_direct_internal_category_and_nearest_ancestor_are_deterministic(self):
        alternative = self._new_template()
        self.root_category.bpi_content_template_id = self.general
        self.child_category.bpi_content_template_id = self.instrumental
        context = self.service.content_template_context(self.product)
        self.assertEqual(context["effective"]["id"], self.instrumental.id)
        self.assertEqual(context["source"]["kind"], "ancestor")
        self.assertEqual(context["source"]["categoryId"], self.child_category.id)
        self.leaf_category.bpi_content_template_id = alternative
        direct = self.service.content_template_context(self.product)
        self.assertEqual(direct["effective"]["id"], alternative.id)
        self.assertEqual(direct["source"]["kind"], "category")
        self.assertEqual(direct["source"]["categoryId"], self.leaf_category.id)

    def test_future_descendant_inherits_without_product_specific_setup(self):
        self.child_category.bpi_content_template_id = self.instrumental
        future_category = self.env["product.category"].create({
            "name": "Nuevo instrumental", "parent_id": self.leaf_category.id,
        })
        product = self.env["product.template"].create({
            "name": "Producto futuro", "categ_id": future_category.id,
        })
        context = self.service.content_template_context(product)
        self.assertEqual(context["effective"]["id"], self.instrumental.id)
        self.assertFalse(product.bpi_content_template_id)

    def test_one_model_serves_multiple_roots_without_name_matching(self):
        other_root = self.env["product.category"].create({
            "name": "Un nombre diferente", "bpi_content_template_id": self.instrumental.id,
        })
        self.child_category.bpi_content_template_id = self.instrumental
        other = self.env["product.template"].create({"name": "Otra ficha", "categ_id": other_root.id})
        self.assertEqual(self.service.content_template_context(other)["effective"]["id"], self.instrumental.id)
        self.assertEqual(self.service.content_template_context(self.product)["effective"]["id"], self.instrumental.id)
        self.assertIn(other_root, self.instrumental.category_ids)
        self.assertIn(self.child_category, self.instrumental.category_ids)

    def test_saved_manual_override_wins_and_explicit_auto_is_read_only(self):
        self.child_category.bpi_content_template_id = self.instrumental
        self.product.bpi_content_template_id = self.general
        before = self._snapshot()
        saved = self.service.content_template_context(self.product)
        self.assertEqual(saved["effective"]["id"], self.general.id)
        self.assertEqual(saved["selectionId"], self.general.id)
        self.assertEqual(saved["source"]["kind"], "manual")
        for automatic in (False, None):
            context = self.service.content_template_context(self.product, template_id=automatic)
            self.assertEqual(context["effective"]["id"], self.instrumental.id)
            self.assertFalse(context["selectionId"])
        self.assertEqual(self._snapshot(), before)

    def test_detail_exposes_internal_category_without_redefining_shop_category(self):
        self.child_category.bpi_content_template_id = self.instrumental
        before = self._snapshot()
        with patch.object(type(self.service), "_openai_json") as provider:
            payload = self.product.bpi_build_payload()
            self.service.content_template_context(self.product, template_id=self.general.id)
        self.assertEqual(payload["product"]["categoryId"], self.public_category.id)
        self.assertEqual(payload["contentTemplates"]["internalCategory"]["id"], self.leaf_category.id)
        self.assertEqual(payload["contentTemplates"]["effective"]["id"], self.instrumental.id)
        self.assertEqual(self._snapshot(), before)
        provider.assert_not_called()

    def test_invalid_selection_rejected_before_provider_or_write(self):
        before = self._snapshot()
        for invalid in (True, -1, 1.5, "1.5", "missing", [], {}, 999999999):
            with self.subTest(selection=invalid), \
                    patch.object(type(self.service), "_openai_json") as provider:
                with self.assertRaises(ValidationError):
                    self.service.generate_content(self.product, template_id=invalid)
                provider.assert_not_called()
        self.assertEqual(self._snapshot(), before)

    def test_revision_changes_on_edit_and_context_exposes_instructions(self):
        template = self._new_template()
        old_revision = template.revision
        template.write({"short_instructions": "Instrucción corta revisada."})
        self.assertGreater(template.revision, old_revision)
        context = self.service.content_template_context(self.product, template_id=template.id)
        self.assertEqual(context["effective"]["revision"], template.revision)
        self.assertEqual(context["effective"]["shortInstructions"], "Instrucción corta revisada.")
        self.assertEqual(context["effective"]["longInstructions"], template.long_instructions)

    def test_unreferenced_model_can_be_duplicated_archived_and_deleted(self):
        template = self._new_template()
        duplicate = template.copy({"name": "Modelo duplicado"})
        self.assertNotEqual(template, duplicate)
        self.assertEqual(duplicate.short_instructions, template.short_instructions)
        self.assertEqual(duplicate.long_instructions, template.long_instructions)
        self.assertFalse(duplicate.category_ids)
        template.active = False
        context = self.service.content_template_context(self.product)
        self.assertNotIn(template.id, [item["id"] for item in context["options"]])
        with self.assertRaises(ValidationError):
            self.service.content_template_context(self.product, template_id=template.id)
        template.unlink()
        self.assertFalse(template.exists())

    def test_general_model_cannot_be_archived_or_deleted(self):
        for operation in (lambda: self.general.write({"active": False}), self.general.unlink):
            with self.assertRaises(UserError):
                operation()
        self.assertTrue(self.general.exists())
        self.assertTrue(self.general.active)

    def test_category_referenced_model_requires_explicit_replacement(self):
        template = self._new_template()
        self.child_category.bpi_content_template_id = template
        for operation in (lambda: template.write({"active": False}), template.unlink):
            with self.assertRaises(UserError):
                operation()
        self.child_category.bpi_content_template_id = self.instrumental
        template.active = False
        self.assertFalse(template.active)

    def test_archived_product_override_still_protects_model_lifecycle(self):
        template = self._new_template()
        self.product.write({"bpi_content_template_id": template.id, "active": False})
        for operation in (lambda: template.write({"active": False}), template.unlink):
            with self.assertRaises(UserError):
                operation()
        self.product.bpi_content_template_id = False
        template.unlink()
        self.assertFalse(template.exists())

    def test_save_content_patch_preserves_override_until_explicit_auto(self):
        self.child_category.bpi_content_template_id = self.instrumental
        payload = self.service.save_content(self.product, {
            "templateId": self.general.id,
            "description": "<p>Resumen guardado explícitamente.</p>",
        })
        self.assertEqual(self.product.bpi_content_template_id, self.general)
        self.assertEqual(payload["contentTemplates"]["selectionId"], self.general.id)
        self.service.save_content(self.product, {"tone": "profesional"})
        self.assertEqual(self.product.bpi_content_template_id, self.general)
        payload = self.service.save_content(self.product, {"templateId": False})
        self.assertFalse(self.product.bpi_content_template_id)
        self.assertEqual(payload["contentTemplates"]["effective"]["id"], self.instrumental.id)
        self.assertIn("Resumen guardado explícitamente", self.product.bpi_ai_generated_description)

    def test_save_content_null_clears_override_without_changing_descriptions(self):
        self.product.bpi_content_template_id = self.instrumental
        before = self._snapshot()
        self.service.save_content(self.product, {"templateId": None})
        after = self._snapshot()
        self.assertFalse(after["bpi_content_template_id"])
        for field in before:
            if field not in {"bpi_content_template_id", "write_date"}:
                self.assertEqual(after[field], before[field], field)

    def test_invalid_override_save_does_not_partially_write_content(self):
        before = self._snapshot()
        with self.assertRaises(ValidationError):
            self.service.save_content(self.product, {
                "templateId": 999999999, "description": "No conservar", "technicalDescription": "No conservar",
            })
        self.assertEqual(self._snapshot(), before)

    def test_save_all_rolls_back_override_and_copy_when_later_stage_fails(self):
        before = self._snapshot()
        with patch.object(type(self.service), "save_seo_payload", side_effect=UserError("Fallo final controlado")):
            with self.assertRaisesRegex(UserError, "Fallo final"):
                self.service.save_all(self.product,
                    product_values={"name": "No conservar"},
                    content_values={"templateId": self.instrumental.id, "description": "No conservar"},
                    seo_data={"seoTitle": "No conservar"},
                )
        self.assertEqual(self._snapshot(), before)

    def test_save_all_commits_override_and_both_descriptions_together(self):
        payload = self.service.save_all(self.product, content_values={
            "templateId": self.instrumental.id,
            "description": "<p>Resumen aprobado.</p>",
            "technicalDescription": "<h3>Ficha aprobada</h3><p>Datos revisados.</p>",
        })
        self.assertEqual(self.product.bpi_content_template_id, self.instrumental)
        self.assertIn("Resumen aprobado", self.product.bpi_ai_generated_description)
        self.assertIn("Ficha aprobada", self.product.bpi_technical_description)
        self.assertEqual(payload["contentTemplates"]["effective"]["id"], self.instrumental.id)

    def test_library_permissions_and_service_guard_are_admin_only(self):
        restricted_service = self.service.with_user(self.non_manager)
        restricted_product = self.product.with_user(self.non_manager)
        with self.assertRaises(AccessError):
            self.templates.with_user(self.non_manager).search([])
        with self.assertRaises(AccessError):
            self.templates.with_user(self.non_manager).create({"name": "No permitido"})
        with self.assertRaises(AccessError):
            restricted_service.content_template_context(restricted_product)
        with patch.object(type(self.service), "_openai_json") as provider:
            with self.assertRaises(AccessError):
                restricted_service.generate_content(restricted_product)
            with self.assertRaises(AccessError):
                restricted_service.save_content(restricted_product, {"templateId": self.instrumental.id})
        provider.assert_not_called()

    def test_cross_company_product_is_rejected_before_generation(self):
        other_company = self.env["res.company"].create({"name": "BPI Template Other Company"})
        other_product = self.env["product.template"].create({
            "name": "Producto de otra empresa", "company_id": other_company.id,
        })
        scoped = self.env(context=dict(self.env.context, allowed_company_ids=self.env.company.ids))
        with patch.object(type(self.service), "_openai_json") as provider, \
                patch("odoo.addons.bader_product_intelligence.controllers.main.request", SimpleNamespace(env=scoped)):
            with self.assertRaises(MissingError):
                scoped["bpi.service"].content_template_context(other_product.with_env(scoped))
            with self.assertRaises(MissingError):
                BaderProductIntelligenceController().generate_content(other_product.id)
        provider.assert_not_called()

    def test_structured_generation_is_read_only_preserves_name_and_fixed_layout(self):
        self.child_category.bpi_content_template_id = self.instrumental
        before = self._snapshot()
        result, prompt = self._generate(self._structured_response(name="No renombrar"))
        tree = html.fragment_fromstring(result["technicalDescriptionHtml"], create_parent="div")
        self.assertEqual(tree.xpath("./h3/text()"), ["Descripción General", "Especificaciones Técnicas"])
        self.assertEqual(len(tree.xpath("./h3[1]/following-sibling::p[following-sibling::h3]")), 2)
        self.assertFalse(tree.xpath(".//h1|.//h2|.//script|.//style"))
        self.assertEqual(result["name"], self.product.name)
        self.assertEqual(result["contentTemplates"]["effective"]["id"], self.instrumental.id)
        self.assertIn("45-70", prompt)
        self.assertNotIn("350-650", prompt)
        self.assertNotIn("OLD_AI_NOT_TECHNICAL_EVIDENCE", prompt)
        self.assertNotIn("OLD_TECH_NOT_CONFIRMED_EVIDENCE", prompt)
        self.assertEqual(self._snapshot(), before)

    def test_missing_confirmed_specs_produces_neutral_notice_not_invented_bullets(self):
        with patch.object(type(self.product), "_bpi_content_facts", return_value=[]):
            result, prompt = self._generate(self._structured_response(), template_id=self.instrumental.id)
        tree = html.fragment_fromstring(result["technicalDescriptionHtml"], create_parent="div")
        self.assertIn("Especificaciones técnicas pendientes de verificación", tree.text_content())
        self.assertFalse(tree.xpath(".//ul|.//li"))
        self.assertTrue(result["warnings"])
        self.assertNotIn("OLD_TECH_NOT_CONFIRMED_EVIDENCE", prompt)

    def test_structured_specifications_render_only_server_fact_values(self):
        facts = [{"id": "weight:test", "label": "Peso confirmado", "value": "0,25 kg"}]
        with patch.object(type(self.product), "_bpi_content_facts", return_value=facts):
            result, unused_prompt = self._generate(
                self._structured_response(specificationIds=["weight:test"]),
                template_id=self.instrumental.id,
            )
        tree = html.fragment_fromstring(result["technicalDescriptionHtml"], create_parent="div")
        self.assertEqual(len(tree.xpath(".//li")), 1)
        self.assertIn("Peso confirmado", tree.xpath(".//li")[0].text_content())
        self.assertIn("0,25 kg", tree.xpath(".//li")[0].text_content())

    def test_invented_specification_id_is_rejected_without_retry_or_save(self):
        before = self._snapshot()
        with patch.object(type(self.product), "_bpi_content_facts", return_value=[]), \
                patch.object(type(self.service), "_openai_json", return_value=self._structured_response(
                    specificationIds=["invented-autoclave-134"],
                )) as provider:
            with self.assertRaises(UserError):
                self.service.generate_content(self.product, template_id=self.instrumental.id)
        provider.assert_called_once()
        self.assertEqual(self._snapshot(), before)

    def test_invalid_structured_response_never_falls_back_to_saved_copy(self):
        invalid_responses = [
            {}, {"description": "Resumen", "technicalDescription": "<p>Formato anterior</p>"},
            self._structured_response(description="<p><br></p>"),
            self._structured_response(description=[]),
            self._structured_response(generalParagraphs=["Solo uno"]),
            self._structured_response(generalParagraphs=["Uno", "Dos", "Tres"]),
            self._structured_response(generalParagraphs=["Uno", ""]),
            self._structured_response(generalParagraphs=["Uno", {}]),
            self._structured_response(generalParagraphs=["Uno", "<h3>Sección no permitida</h3>"]),
            self._structured_response(generalParagraphs=["Uno", "- lista no permitida"]),
            self._structured_response(generalParagraphs=["Uno", "Dos\nTres"]),
            self._structured_response(specificationIds="not-a-list"),
        ]
        before = self._snapshot()
        for response in invalid_responses:
            with self.subTest(response=response), \
                    patch.object(type(self.service), "_openai_json", return_value=response) as provider:
                with self.assertRaises(UserError):
                    self.service.generate_content(self.product, template_id=self.instrumental.id)
                provider.assert_called_once()
        self.assertEqual(self._snapshot(), before)

    def test_generic_template_keeps_legacy_response_keys_and_word_targets(self):
        short = "<p>Resumen comercial breve para revisión.</p>"
        long = "<h3>Características</h3><p>Texto técnico confirmado para revisión.</p>"
        result, prompt = self._generate({
            "name": self.product.name, "description": short, "technicalDescription": long,
        })
        self.assertIn("45-70 palabras", prompt)
        self.assertIn("350-650 palabras", prompt)
        self.assertEqual(result["descriptionHtml"], short)
        self.assertEqual(result["technicalDescriptionHtml"], long)
        for key in ("name", "description", "technicalDescription", "tone", "audience"):
            self.assertIn(key, result)

    def test_generic_invalid_or_empty_html_does_not_return_old_content_as_success(self):
        before = self._snapshot()
        for response in ({}, {"description": "<p><br></p>", "technicalDescription": "<p>Texto</p>"},
                         {"description": "<p>Texto</p>", "technicalDescription": []}):
            with self.subTest(response=response), \
                    patch.object(type(self.service), "_openai_json", return_value=response) as provider:
                with self.assertRaises(UserError):
                    self.service.generate_content(self.product)
                provider.assert_called_once()
        self.assertEqual(self._snapshot(), before)

    def test_stale_template_revision_is_rejected_before_paid_request(self):
        revision = self.instrumental.revision
        self.instrumental.write({"short_instructions": self.instrumental.short_instructions + "\nRevisión nueva."})
        with patch.object(type(self.service), "_openai_json") as provider:
            with self.assertRaises(UserError):
                self.service.generate_content(self.product,
                    template_id=self.instrumental.id, template_revision=revision,
                )
        provider.assert_not_called()

    def test_template_changed_during_generation_discards_result_without_retry(self):
        revision = self.instrumental.revision
        before = self._snapshot()

        def changed_template(*args, **kwargs):
            self.instrumental.write({"long_instructions": self.instrumental.long_instructions + "\nNueva revisión."})
            return self._structured_response()

        with patch.object(type(self.service), "_openai_json", side_effect=changed_template) as provider:
            with self.assertRaises(UserError):
                self.service.generate_content(self.product,
                    template_id=self.instrumental.id, template_revision=revision,
                )
        provider.assert_called_once()
        self.assertEqual(self._snapshot(), before)

    def test_word_targets_warn_without_automatic_paid_retry(self):
        result, unused_prompt = self._generate(self._structured_response(description="Resumen breve."),
            template_id=self.instrumental.id,
        )
        self.assertTrue(result["warnings"])
        self.assertIn("Resumen breve", result["descriptionHtml"])

    def test_missing_native_measurements_and_old_ai_copy_are_not_facts(self):
        self.product.write({"weight": 0, "volume": 0})
        facts = self.product._bpi_content_facts()
        self.assertFalse(any(item["id"] in {"weight", "volume"} for item in facts))
        self.assertNotIn("OLD_AI_NOT_TECHNICAL_EVIDENCE", str(facts))
        self.assertNotIn("OLD_TECH_NOT_CONFIRMED_EVIDENCE", str(facts))

    def test_native_measurements_use_configured_units_and_decimal_comma(self):
        kilogram = self.env.ref("uom.product_uom_kgm")
        cubic_meter = self.env.ref("uom.product_uom_cubic_meter")
        # QAS native Stock Weight/Volume precision is two decimal places.
        # Exercise a representable saved value, not precision Odoo discarded.
        self.product.write({"weight": 1.25, "volume": 0.03})
        with patch.object(type(self.product), "_get_weight_uom_id_from_ir_config_parameter", return_value=kilogram), \
                patch.object(type(self.product), "_get_volume_uom_id_from_ir_config_parameter", return_value=cubic_meter):
            facts = {item["id"]: item for item in self.product._bpi_content_facts()}
        self.assertEqual(facts["weight"]["value"], "1,25 kg")
        self.assertEqual(facts["volume"]["value"], "0,03 m³")

    def test_incompatible_or_unknown_measurement_unit_is_not_guessed(self):
        self.product.write({"weight": 1.25})
        for unit in (self.env["uom.uom"], self.env.ref("uom.product_uom_unit")):
            with self.subTest(unit=unit), \
                    patch.object(type(self.product), "_get_weight_uom_id_from_ir_config_parameter", return_value=unit):
                facts = self.product._bpi_content_facts()
            self.assertFalse(any(item["id"] == "weight" for item in facts))

    def test_variant_facts_are_scoped_to_each_variant_not_one_shared_spec(self):
        attribute = self.env["product.attribute"].create({"name": "Color para modelos", "create_variant": "always"})
        values = self.env["product.attribute.value"].create([
            {"name": "Verde", "attribute_id": attribute.id},
            {"name": "Azul", "attribute_id": attribute.id},
        ])
        product = self.env["product.template"].create({
            "name": "Producto de dos variantes para modelos", "categ_id": self.leaf_category.id,
            "attribute_line_ids": [(0, 0, {"attribute_id": attribute.id, "value_ids": [(6, 0, values.ids)]})],
        })
        variants = product.product_variant_ids.sorted("id")
        self.assertEqual(len(variants), 2)
        variants[0].write({"default_code": "MODEL-VAR-A", "weight": 1.25})
        variants[1].write({"default_code": "MODEL-VAR-B", "weight": 2.5})
        with patch.object(type(product), "_get_weight_uom_id_from_ir_config_parameter", return_value=self.env.ref("uom.product_uom_kgm")):
            facts = {item["id"]: item for item in product._bpi_content_facts()}
        self.assertNotIn("weight", facts)
        for variant, expected in zip(variants, ("1,25 kg", "2,5 kg")):
            fact = facts["variant:%s:weight" % variant.id]
            self.assertEqual(fact["value"], expected)
            self.assertIn(variant.default_code, fact["label"])
            attributes = [item for key, item in facts.items() if key.startswith("variant:%s:attribute:" % variant.id)]
            self.assertEqual(len(attributes), 1)
        self.assertFalse(product.bpi_content_template_id)

    def test_pack_facts_expose_saved_composition_without_relabeling_component_properties(self):
        component = self.env["product.template"].create({
            "name": "Componente confirmado del Pack", "default_code": "MODEL-PACK-COMP", "weight": 12,
        })
        product = self.env["product.template"].create({
            "name": "Pack de prueba de modelos", "pack_ok": True,
            "pack_type": "detailed", "pack_component_price": "ignored",
            "categ_id": self.leaf_category.id,
        })
        variant = product.product_variant_id
        variant.write({"pack_line_ids": [(0, 0, {
            "product_id": component.product_variant_id.id, "quantity": 2.5,
        })]})
        before_lines = variant.pack_line_ids.read(["product_id", "quantity"])
        facts = product._bpi_content_facts()
        components = [item for item in facts if item["id"].startswith("pack:")]
        self.assertEqual(len(components), 1)
        self.assertIn("2,5", components[0]["value"])
        self.assertIn(component.name, components[0]["value"])
        self.assertIn(component.uom_id.name, components[0]["value"])
        self.assertNotIn("12 kg", components[0]["value"])
        self.assertEqual(variant.pack_line_ids.read(["product_id", "quantity"]), before_lines)

    def test_library_word_targets_and_empty_instructions_are_validated(self):
        for values in ({"short_min_words": -1}, {"short_min_words": 71, "short_max_words": 70},
                       {"long_min_words": 700, "long_max_words": 350},
                       {"short_instructions": "   "}, {"long_instructions": "   "}):
            with self.subTest(values=values), self.assertRaises(ValidationError), self.env.cr.savepoint():
                self._new_template(**values)

    def test_model_association_fields_cannot_bypass_admin_guard(self):
        with self.assertRaises(AccessError):
            self.product.with_user(self.non_manager).write({"bpi_content_template_id": self.instrumental.id})
        with self.assertRaises(AccessError):
            self.child_category.with_user(self.non_manager).write({"bpi_content_template_id": self.instrumental.id})
        self.assertFalse(self.product.bpi_content_template_id)
        self.assertFalse(self.child_category.bpi_content_template_id)

    def test_archived_model_cannot_be_assigned_through_generic_orm_write(self):
        template = self._new_template()
        template.active = False
        for record in (self.product, self.child_category):
            with self.subTest(model=record._name), self.assertRaises(UserError):
                record.write({"bpi_content_template_id": template.id})
            self.assertFalse(record.bpi_content_template_id)

    def test_explicit_generation_selection_does_not_persist_manual_override(self):
        self.product.bpi_content_template_id = self.general
        before = self._snapshot()
        result, unused_prompt = self._generate(self._structured_response(),
            template_id=self.instrumental.id, template_revision=self.instrumental.revision,
        )
        self.assertEqual(result["contentTemplates"]["effective"]["id"], self.instrumental.id)
        self.assertEqual(result["contentTemplates"]["selectionId"], self.instrumental.id)
        self.assertEqual(self._snapshot(), before)
        self.assertEqual(self.product.bpi_content_template_id, self.general)

    def test_controller_preserves_omitted_selection_and_explicit_false_null(self):
        self.child_category.bpi_content_template_id = self.instrumental
        self.product.bpi_content_template_id = self.general
        controller = BaderProductIntelligenceController()
        with patch("odoo.addons.bader_product_intelligence.controllers.main.request", SimpleNamespace(env=self.env)), \
                patch.object(type(self.service), "_openai_json") as provider:
            saved = controller.content_template_context(self.product.id)
            self.assertEqual(saved["selectionId"], self.general.id)
            for automatic in (False, None):
                context = controller.content_template_context(self.product.id, template_id=automatic)
                self.assertFalse(context["selectionId"])
                self.assertEqual(context["effective"]["id"], self.instrumental.id)
        provider.assert_not_called()
        self.assertEqual(self.product.bpi_content_template_id, self.general)

    def test_fresh_transaction_metadata_can_reject_other_revision_without_replay(self):
        context = self.service.content_template_context(self.product, template_id=self.instrumental.id)
        context["effective"]["revision"] += 1
        before = self._snapshot()
        with patch.object(type(self.service), "_content_template_fresh_context", return_value=context) as fresh, \
                patch.object(type(self.service), "_openai_json", return_value=self._structured_response()) as provider:
            with self.assertRaises(UserError):
                self.service.generate_content(self.product, template_id=self.instrumental.id)
        fresh.assert_called_once()
        provider.assert_called_once()
        self.assertEqual(self._snapshot(), before)

    def test_repeated_specification_ids_are_rejected_not_duplicated(self):
        facts = [{"id": "weight:test", "label": "Peso", "value": "1 kg"}]
        with patch.object(type(self.product), "_bpi_content_facts", return_value=facts), \
                patch.object(type(self.service), "_openai_json", return_value=self._structured_response(
                    specificationIds=["weight:test", "weight:test"],
                )) as provider:
            with self.assertRaises(UserError):
                self.service.generate_content(self.product, template_id=self.instrumental.id)
        provider.assert_called_once()

    def test_library_category_tags_assign_replace_and_clear_without_reclassifying_products(self):
        template = self._new_template()
        self.child_category.bpi_content_template_id = self.instrumental
        before = self._snapshot()
        template.write({"category_selection_ids": [(6, 0, self.child_category.ids)]})
        self.assertEqual(self.child_category.bpi_content_template_id, template)
        self.assertEqual(template.category_ids, self.child_category)
        self.assertEqual(template.category_selection_ids, self.child_category)
        self.assertNotIn(self.child_category, self.instrumental.category_ids)
        self.assertEqual(self.service.content_template_context(self.product)["effective"]["id"], template.id)
        self.assertEqual(self._snapshot(), before)
        template.write({"category_selection_ids": [(5, 0, 0)]})
        self.assertFalse(self.child_category.bpi_content_template_id)
        self.assertFalse(template.category_ids)
        self.assertEqual(self.service.content_template_context(self.product)["effective"]["id"], self.general.id)
        self.assertEqual(self._snapshot(), before)

    def test_blocked_archive_does_not_apply_other_recipe_changes(self):
        template = self._new_template()
        self.child_category.bpi_content_template_id = template
        before = template.read(["name", "short_instructions", "active", "revision"])[0]
        with self.assertRaises(UserError):
            template.write({"active": False, "name": "No conservar", "short_instructions": "No conservar"})
        self.assertEqual(template.read(["name", "short_instructions", "active", "revision"])[0], before)
        self.assertEqual(self.child_category.bpi_content_template_id, template)

    def test_native_stock_manager_can_create_products_and_categories_without_library_access(self):
        self.assertFalse(self.stock_manager.has_group("base.group_system"))
        self.root_category.bpi_content_template_id = self.instrumental
        with self.assertRaises(AccessError):
            self.templates.with_user(self.stock_manager).search([])
        category = self.env["product.category"].with_user(self.stock_manager).create({
            "name": "Categoría nativa creada por almacén", "parent_id": self.root_category.id,
        }).with_env(self.env)
        product = self.env["product.template"].with_user(self.stock_manager).create({
            "name": "Producto nativo creado por almacén", "categ_id": category.id,
        }).with_env(self.env)
        self.assertFalse(category.bpi_content_template_id)
        self.assertFalse(product.bpi_content_template_id)
        self.assertEqual(self.service.content_template_context(product)["effective"]["id"], self.instrumental.id)

    def test_native_category_copy_drops_admin_override_and_inherits_parent(self):
        self.assertFalse(self.stock_manager.has_group("base.group_system"))
        self.root_category.bpi_content_template_id = self.general
        self.child_category.bpi_content_template_id = self.instrumental
        originals = ((self.child_category, self.general), (self.leaf_category, self.instrumental))
        for original, expected in originals:
            with self.subTest(original=original.id):
                duplicate = original.with_user(self.stock_manager).copy({
                    "name": "Copia nativa de categoría %s" % original.id,
                }).with_env(self.env)
                self.assertFalse(duplicate.bpi_content_template_id)
                self.assertEqual(duplicate.parent_id, original.parent_id)
                product = self.env["product.template"].create({
                    "name": "Producto en categoría copiada", "categ_id": duplicate.id,
                })
                self.assertEqual(self.service.content_template_context(product)["effective"]["id"], expected.id)
        self.assertEqual(self.child_category.bpi_content_template_id, self.instrumental)
        self.assertFalse(self.leaf_category.bpi_content_template_id)

    def test_native_product_copy_drops_manual_override_and_keeps_category(self):
        self.assertFalse(self.stock_manager.has_group("base.group_system"))
        self.child_category.bpi_content_template_id = self.instrumental
        for selection in (False, self.general.id):
            with self.subTest(selection=selection):
                original = self.env["product.template"].create({
                    "name": "Producto para copia nativa %s" % selection,
                    "categ_id": self.leaf_category.id, "bpi_content_template_id": selection,
                })
                duplicate = original.with_user(self.stock_manager).copy({
                    "name": "Copia nativa %s" % original.id,
                }).with_env(self.env)
                self.assertFalse(duplicate.bpi_content_template_id)
                self.assertEqual(duplicate.categ_id, original.categ_id)
                self.assertEqual(self.service.content_template_context(duplicate)["effective"]["id"], self.instrumental.id)
                self.assertEqual(original.bpi_content_template_id.id or False, selection)

    def test_general_specs_separates_fields_and_includes_all_saved_measurements(self):
        recipe = self._new_template(format="general_specs", short_min_words=0, short_max_words=0)
        variant = self.product.product_variant_id
        self.env["bpi.product.specification"]._save_rows(self.product, [{
            "variantId": variant.id, "revision": 0, "values": {"length": 17, "weight": 17, "height": 1.5},
        }])
        before = self._snapshot()
        result, prompt = self._generate(self._structured_response(), template_id=recipe.id)
        short, long = result["descriptionHtml"], result["technicalDescriptionHtml"]
        self.assertEqual(len(html.fragment_fromstring(short, create_parent="div").xpath("./p")), 2)
        self.assertNotIn("Descripción General", long)
        self.assertIn("Especificaciones Técnicas", long)
        for value in ("17 cm", "17 g", "1,5 cm"):
            self.assertIn(value, long)
            self.assertIn(value, prompt)
        self.assertNotIn("OLD_AI_NOT_TECHNICAL_EVIDENCE", prompt)
        self.assertFalse(result["warnings"])
        self.assertEqual(before, self._snapshot())

    def test_general_specs_invalid_ids_or_prose_do_not_retry_or_save(self):
        recipe = self._new_template(format="general_specs")
        before = self._snapshot()
        for changes in ({"specificationIds": ["invented"]}, {"specificationIds": "weight"},
                        {"generalParagraphs": ["<script>x</script>", "text"]},
                        {"generalParagraphs": ["only one"]}):
            with patch.object(type(self.service), "_openai_json", return_value=self._structured_response(**changes)) as provider:
                with self.assertRaises(UserError):
                    self.service.generate_content(self.product, template_id=recipe.id)
                provider.assert_called_once()
            self.assertEqual(before, self._snapshot())

    def test_general_specs_unknown_facts_are_pending_not_zero(self):
        recipe = self._new_template(format="general_specs", short_min_words=0, short_max_words=0)
        result, unused = self._generate(self._structured_response(), template_id=recipe.id)
        self.assertIn("pendientes de verificación", result["technicalDescriptionHtml"])
        self.assertNotIn("0 cm", result["technicalDescriptionHtml"])
        self.assertEqual(len(result["warnings"]), 1)

    def test_editorial_receipt_is_private_and_not_generation_evidence(self):
        self.product.bpi_editorial_import = {
            "date": "2026-09-15 10:00:00", "sku": "fixture", "differences": [],
            "contentHash": self.product._bpi_editorial_content_hash(),
            "documentText": "APPROVED_PROSE_IS_NOT_SAVED_MEASUREMENT",
        }
        receipt = self.product.bpi_build_payload()["product"]["editorialImport"]
        self.assertFalse(receipt["changedSinceImport"])
        self.assertNotIn("documentText", receipt)
        result, prompt = self._generate({"description": "Commercial", "technicalDescription": "Technical"})
        self.assertNotIn("APPROVED_PROSE", prompt)
        self.assertTrue(any("documento importado" in x for x in result["warnings"]))
        self.product.bpi_technical_description = "<p>Edited after import</p>"
        self.assertTrue(self.product.bpi_build_payload()["product"]["editorialImport"]["changedSinceImport"])
        with self.assertRaises(AccessError):
            self.product.with_user(self.non_manager).read(["bpi_editorial_import"])
