from . import product_template
from . import ir_ui_view
from . import product_public_category
from . import product_intelligence
from . import ai_job
from . import res_config_settings
from . import dashboard
from . import meli_provider
from . import content_template
from . import content_generation
from . import technical_specification
from . import technical_import
from . import editorial_import
from . import product_documents
from . import taxonomy
from . import taxonomy_search
from . import description_layout
from . import content_studio
